### ISSUE TITLE
Preparse an asset source field

### ISSUE THREAD

**Issue by pl-mnm** [aelvan/Preparse-Field-Craft#37]
I'd like to preparse an image to get a dominant color using imager, so I added the following to a preparse field linked to an asset source:

```
{% set smallImg = craft.imager.transformImage(element, { width: 100 }) %}
{{ craft.imager.getDominantColor(smallImg) }}
```

However it won't work when I upload the image or save the entry. I have to manually go and save the image, even with `Parse before save` enabled. Is there a way around this?

**Comment by aelvan** [comment]
This is due to an underlying issue in Craft, I've posted it [here](https://github.com/craftcms/cms/issues/3167).

**Comment by aelvan** [comment]
This has been fixed in 1.0.2.

**Comment by pl-mnm** [comment]
Thanks, however still no luck after updating both the plugin and Craft (3.0.18). Is there any other info that would help pinpointing the problem?
